version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

workflows:
  check_and_coverage:
    jobs:
      - build:
          context:
            - github

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx1g
      TERM: dumb

    steps:
      - run: sudo apt update && sudo apt install -y libpangoft2-1.0-0

      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "buildSrc/build.gradle" }}-{{ checksum "sundriesFx/build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "buildSrc/build.gradle" }}-{{ checksum "sundriesFx/build.gradle" }}

      - run:
          gradle check jacocoTestReport -PheadlessFxMode=true --info
      - codecov/upload:
          file: sundriesFx/build/reports/jacoco/test/jacocoTestReport.xml

